name: Automated Tests
on: [pull_request]
jobs:
  jest:
    name: Vitest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/jod"

      - run: npm ci

      - run: npm run test
